### ISSUE TITLE
dotEnvLoader not exported from module

### ISSUE THREAD

**Issue by fiqrisr** [alxevvv/nest-zod-config#3]
Hi, i got this error, any idea how to solve it?
Thanks

![image](https://github.com/alxevvv/nest-zod-config/assets/30799382/50d125e5-ec5d-4559-afa0-0328f3fd42fd)

**Comment by alxevvv** [comment]
Hi
Maybe it happened because of barrel re-export from dependency library.
I created a patch with possible fix, please try to install version 1.0.1, hope it will help.

**Comment by fiqrisr** [comment]
Thank you, it is solved now!
